name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: " Thanks for the repository contribution, Always remember to raise pull request "
        pr-message: " Thank you, We'll have a look at the request and get back to you ASAP"
